# Generated by Django 5.1.2 on 2024-11-04 06:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='illustrations/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('notice', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('administrators', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('target_time', models.DateTimeField(db_index=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=40)),
                ('max_participants', models.IntegerField(default=2)),
                ('min_participants', models.IntegerField(default=2)),
                ('participants', models.ManyToManyField(related_name='joined_user', to=settings.AUTH_USER_MODEL)),
                ('sponser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsered_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('click', models.IntegerField(db_index=True, default=0)),
                ('likes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forum')),
                ('images', models.ManyToManyField(blank=True, null=True, related_name='post_images', to='forum.postimage')),
                ('tag', models.ManyToManyField(to='forum.tag')),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_denied', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('state', models.IntegerField(default=0)),
                ('sponser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_group_requested_user', to=settings.AUTH_USER_MODEL)),
                ('target_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_group_request', to='forum.grouppost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'target_post'), name='unique_user_targetpost')],
            },
        ),
    ]
